<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <SpaRoot>ClientApp\</SpaRoot>
    <SpaProxyServerUrl>https://localhost:44413</SpaProxyServerUrl>
    <SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="8.0.0-preview.6.23329.11">
      <!-- The SPA Proxy is only used at development time -->
      <Publish>false</Publish>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <!-- Don't publish the SPA source files, but do show them in the project files list -->
    <Content Remove="$(SpaRoot)**" />
    <None Remove="$(SpaRoot)**" />
    <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="ClientApp\src\app\admin\AuthStatus.ts" />
    <None Remove="ClientApp\src\app\auth\login\LoginRequest.ts" />
    <None Remove="ClientApp\src\app\auth\login\LoginResponse.ts" />
    <None Remove="ClientApp\src\app\auth\register\EmailValidationRequest.ts" />
    <None Remove="ClientApp\src\app\auth\register\EmailValidationResponse.ts" />
    <None Remove="ClientApp\src\app\auth\register\PasswordValidationRequest.ts" />
    <None Remove="ClientApp\src\app\auth\register\PasswordValidationResponse.ts" />
    <None Remove="ClientApp\src\app\auth\register\RegisterRequest.ts" />
    <None Remove="ClientApp\src\app\auth\register\RegisterResponse.ts" />
    <None Remove="ClientApp\src\app\auth\register\UsernameCheckResponse.ts" />
    <None Remove="ClientApp\src\app\brokers\Broker.ts" />
    <None Remove="ClientApp\src\app\market-overview\chart\PortfolioIncome.ts" />
    <None Remove="ClientApp\src\app\market-overview\chart\PriceTrend.ts" />
    <None Remove="ClientApp\src\app\market-overview\chart\SectorDistribution.ts" />
    <None Remove="ClientApp\src\app\market-overview\chart\Security.ts" />
    <None Remove="ClientApp\src\app\market-overview\chart\SecurityAllocation.ts" />
    <None Remove="ClientApp\src\app\market-overview\MarketOverview.ts" />
    <None Remove="ClientApp\src\app\market-overview\SecurityPerformance.ts" />
    <None Remove="ClientApp\src\app\portfolios\CreatePortfolio.ts" />
    <None Remove="ClientApp\src\app\portfolios\portfolio-returns\PortfolioReturns.ts" />
    <None Remove="ClientApp\src\app\portfolios\portfolio-returns\PortfolioReturnsSummary.ts" />
    <None Remove="ClientApp\src\app\portfolios\Portfolio.ts" />
    <None Remove="ClientApp\src\app\portfolios\PortfolioAnalytics.ts" />
    <None Remove="ClientApp\src\app\portfolios\SecuritiesPriceTrend.ts" />
    <None Remove="ClientApp\src\app\portfolios\UpdatePortfolio.ts" />
    <None Remove="ClientApp\src\app\register.service.ts" />
    <None Remove="ClientApp\src\app\securities\CreateSecurity.ts" />
    <None Remove="ClientApp\src\app\securities\Issuer.ts" />
    <None Remove="ClientApp\src\app\securities\Security.ts" />
    <None Remove="ClientApp\src\app\securities\SecurityDailyPrices.ts" />
    <None Remove="ClientApp\src\app\securities\TypeSecurity.ts" />
    <None Remove="ClientApp\src\app\security-filter\analyst.guard.ts" />
    <None Remove="ClientApp\src\app\security-filter\FilteredSecurity.ts" />
    <None Remove="ClientApp\src\app\security-filter\Sector.ts" />
    <None Remove="ClientApp\src\app\security-filter\security-filter.service.ts" />
    <None Remove="ClientApp\src\app\shared\brokers-translate.pipe.ts" />
    <None Remove="ClientApp\src\app\shared\db-value-translate.pipe.ts" />
    <None Remove="ClientApp\src\app\shared\issuers-translate.pipe.ts" />
    <None Remove="ClientApp\src\app\shared\sectors-translate.pipe.ts" />
    <None Remove="ClientApp\src\app\shared\security-filter-metrics-translate.pipe.ts" />
    <None Remove="ClientApp\src\app\theme.service.ts" />
    <None Remove="ClientApp\src\app\transactions\PortfolioTableView.ts" />
    <None Remove="ClientApp\src\app\transactions\PortfolioValue.ts" />
    <None Remove="ClientApp\src\app\transactions\Transaction.ts" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\PriceFlowSecurity\PriceFlowSecurity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <TypeScriptCompile Include="ClientApp\src\app\admin\AuthStatus.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\auth\login\LoginRequest.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\auth\login\LoginResponse.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\auth\register\EmailValidationRequest.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\auth\register\EmailValidationResponse.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\auth\register\PasswordValidationRequest.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\auth\register\PasswordValidationResponse.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\auth\register\register.service.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\auth\register\RegisterRequest.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\auth\register\RegisterResponse.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\auth\register\UsernameCheckResponse.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\brokers\Broker.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\market-overview\chart\PortfolioIncome.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\market-overview\chart\PriceTrend.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\market-overview\chart\SectorDistribution.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\market-overview\chart\Security.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\market-overview\chart\SecurityAllocation.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\market-overview\MarketOverview.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\market-overview\SecurityPerformance.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\portfolios\CreatePortfolio.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\portfolios\portfolio-returns\PortfolioReturns.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\portfolios\portfolio-returns\PortfolioReturnsSummary.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\portfolios\Portfolio.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\portfolios\PortfolioAnalytics.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\portfolios\SecuritiesPriceTrend.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\portfolios\UpdatePortfolio.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\securities\CreateSecurity.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\securities\Issuer.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\securities\Security.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\securities\SecurityDailyPrices.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\securities\TypeSecurity.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\security-filter\analyst.guard.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\security-filter\FilteredSecurity.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\security-filter\Sector.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\security-filter\security-filter.service.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\shared\brokers-translate.pipe.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\shared\db-value-translate.pipe.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\shared\issuers-translate.pipe.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\shared\sectors-translate.pipe.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\shared\security-filter-metrics-translate.pipe.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\theme.service.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\transactions\PortfolioTableView.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\transactions\PortfolioValue.ts" />
    <TypeScriptCompile Include="ClientApp\src\app\transactions\Transaction.ts" />
  </ItemGroup>

    <Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
  </Target>
  
  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --configuration production" />

    <!-- Include the newly-built files in the publish output -->
    <ItemGroup>
      <DistFiles Include="$(SpaRoot)dist\**; $(SpaRoot)dist-server\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>wwwroot\%(RecursiveDir)%(FileName)%(Extension)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
