CREATE TABLE [dbo].[TipHV]
(
	[Id] INT IDENTITY(1, 1) NOT NULL, 
    [Ime] NVARCHAR(10) NOT NULL,
	[DateModified] DATETIME NOT NULL CONSTRAINT df_TipHV_DateModified DEFAULT (SYSUTCDATETIME()),

	CONSTRAINT pk_TipHV PRIMARY KEY (Id),
	CONSTRAINT un_TipHV_Ime UNIQUE (Ime)
)
