CREATE TABLE [dbo].[Ulogi]
(
	[Id] INT IDENTITY(1, 1) NOT NULL, 
    [Ime] NVARCHAR(50) NOT NULL,
	[DateModified] DATETIME NOT NULL CONSTRAINT df_Ulogi_DateModified DEFAULT (SYSUTCDATETIME()),

	CONSTRAINT pk_Ulogi PRIMARY KEY (Id),
	CONSTRAINT un_Ulogi_Ime UNIQUE (Ime)
)
