CREATE TABLE [dbo].[Hub_TipHV]
(
	TipHV_HK CHAR(32) NOT NULL,
	Ime NVARCHAR(10) NOT NULL,
	LoadDate DATETIME2 NOT NULL,
	RecordSource NVARCHAR(50) NOT NULL,

	CONSTRAINT pk_Hub_TipHV PRIMARY KEY (TipHV_HK),
	CONSTRAINT un_Hub_TipHV_Ime UNIQUE (Ime)
)
